version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: email-templates
    versions:
    - 8.0.3
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
