version: '3'

services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clock_of_change
    ports:
      - 3306:3306

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  coc-api:
    image: clock-of-change-api
    build:
      context: .
    volumes:
      - ".:/home/node/coc-api"
      - "/home/node/coc-api/node_modules"
    ports:
      - 1337:1337
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=clock_of_change
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USER=mailer
      - MAIL_PASS=123456
    depends_on:
      - db
      - mailhog
    command: bash -c "wait-on tcp:db:3306 && db-migrate up && npm run start"
