version: '3'

services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clock_of_change
    ports:
      - 3306:3306

  coc-api:
    image: clock-of-change-api
    build:
      context: .
    volumes:
      - ".:/home/node/coc-api"
      - "/home/node/coc-api/node_modules"
    ports:
      - 1337:1337
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB=clock_of_change
      - MYSQL_USER=root
      - MYSQL_PASS=123456
    depends_on:
      - db
    command: bash -c "db-migrate up && npm run start"
    #entrypoint: /docker-entrypoint.sh
